version: "3.3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    expose:
      - "9000"

  db:
    image: mariadb:10.11.2-jammy
    volumes:
      - ./docker/db/app-data/:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=1
      - MARIADB_USER=app
      - MARIADB_PASSWORD=1
      - MARIADB_DATABASE=app
    ports:
      - "3306:3306"

volumes:
  dbdata:
